trigger:
- master

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
- task: NuGetToolInstaller@1

- task: NuGetCommand@2
  inputs:
    restoreSolution: '$(solution)'

- task: DotNetCoreCLI@2
  displayName: "Build projects"
  inputs:
    command: build
    configuration: $(buildConfiguration)
    projects: "**/*.csproj"
    feedsToUse: "select"
    vstsFeed: "Content"

- task: DotNetCoreCLI@2
  displayName: "Publish backend"
  inputs:
    command: publish
    publishWebProjects: False
    projects: "**/Irrelephand.DnB.Server.csproj"
    arguments: "--configuration $(buildConfiguration) --output $(Build.ArtifactStagingDirectory)/backend"
    zipAfterPublish: False

- task: PublishBuildArtifacts@1
  inputs:
    artifact: backend-drop
    path: "$(Build.ArtifactStagingDirectory)/backend"

- task: DotNetCoreCLI@2
  displayName: "Publish frontend"
  inputs:
    command: publish
    publishWebProjects: False
    projects: "**/Irrelephand.DnB.Client.csproj"
    arguments: "--configuration $(buildConfiguration) --output $(Build.ArtifactStagingDirectory)/frontend"
    zipAfterPublish: False

- task: PublishBuildArtifacts@1
  inputs:
    artifact: frontend-drop
    path: "$(Build.ArtifactStagingDirectory)/frontend"